#!/bin/bash
# sudo yum install -y httpd
# sudo yum install -y php
sudo yum install -y php-mysql
sudo yum install -y php-gd
sudo yum install -y php-mbstring
echo "Directory Index index.php" >> /etc/httpd/conf/httpd.conf
